// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSessionsInRange = `-- name: CountSessionsInRange :one
SELECT COUNT(*)::bigint AS sessions
FROM activities
WHERE user_id = $1 AND performed_at >= $2 AND performed_at < $3
`

type CountSessionsInRangeParams struct {
	UserID uuid.UUID          `json:"userId"`
	Start  pgtype.Timestamptz `json:"start"`
	Stop   pgtype.Timestamptz `json:"stop"`
}

func (q *Queries) CountSessionsInRange(ctx context.Context, arg CountSessionsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsInRange, arg.UserID, arg.Start, arg.Stop)
	var sessions int64
	err := row.Scan(&sessions)
	return sessions, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (user_id, kind, title, performed_at, load, planned, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, kind, title, performed_at, load, planned, notes, created_at, updated_at
`

type CreateActivityParams struct {
	UserID      uuid.UUID          `json:"userId"`
	Kind        string             `json:"kind"`
	Title       string             `json:"title"`
	PerformedAt pgtype.Timestamptz `json:"performedAt"`
	Load        int32              `json:"load"`
	Planned     bool               `json:"planned"`
	Notes       string             `json:"notes"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.PerformedAt,
		arg.Load,
		arg.Planned,
		arg.Notes,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.PerformedAt,
		&i.Load,
		&i.Planned,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (activity_id, name, note, position)
VALUES ($1, $2, $3, $4)
RETURNING id, activity_id, name, note, position
`

type CreateExerciseParams struct {
	ActivityID uuid.UUID `json:"activityId"`
	Name       string    `json:"name"`
	Note       string    `json:"note"`
	Position   int32     `json:"position"`
}

// ── Lift details ────────────────────────────────────────────────────────────
func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.ActivityID,
		arg.Name,
		arg.Note,
		arg.Position,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.Name,
		&i.Note,
		&i.Position,
	)
	return i, err
}

const createLiftSet = `-- name: CreateLiftSet :one
INSERT INTO lift_sets (exercise_id, weight_kg, reps, done, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, exercise_id, weight_kg, reps, done, position
`

type CreateLiftSetParams struct {
	ExerciseID uuid.UUID      `json:"exerciseId"`
	WeightKg   pgtype.Numeric `json:"weightKg"`
	Reps       int32          `json:"reps"`
	Done       bool           `json:"done"`
	Position   int32          `json:"position"`
}

func (q *Queries) CreateLiftSet(ctx context.Context, arg CreateLiftSetParams) (LiftSet, error) {
	row := q.db.QueryRow(ctx, createLiftSet,
		arg.ExerciseID,
		arg.WeightKg,
		arg.Reps,
		arg.Done,
		arg.Position,
	)
	var i LiftSet
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.WeightKg,
		&i.Reps,
		&i.Done,
		&i.Position,
	)
	return i, err
}

const createRunDetail = `-- name: CreateRunDetail :one
INSERT INTO run_details (activity_id, distance_m, duration_s, avg_pace_s_per_km, avg_hr, calories)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING activity_id, distance_m, duration_s, avg_pace_s_per_km, avg_hr, calories
`

type CreateRunDetailParams struct {
	ActivityID    uuid.UUID `json:"activityId"`
	DistanceM     int32     `json:"distanceM"`
	DurationS     int32     `json:"durationS"`
	AvgPaceSPerKm int32     `json:"avgPaceSPerKm"`
	AvgHr         int32     `json:"avgHr"`
	Calories      int32     `json:"calories"`
}

// ── Run details ─────────────────────────────────────────────────────────────
func (q *Queries) CreateRunDetail(ctx context.Context, arg CreateRunDetailParams) (RunDetail, error) {
	row := q.db.QueryRow(ctx, createRunDetail,
		arg.ActivityID,
		arg.DistanceM,
		arg.DurationS,
		arg.AvgPaceSPerKm,
		arg.AvgHr,
		arg.Calories,
	)
	var i RunDetail
	err := row.Scan(
		&i.ActivityID,
		&i.DistanceM,
		&i.DurationS,
		&i.AvgPaceSPerKm,
		&i.AvgHr,
		&i.Calories,
	)
	return i, err
}

const createRunSplit = `-- name: CreateRunSplit :one
INSERT INTO run_splits (activity_id, km, pace_s, hr)
VALUES ($1, $2, $3, $4)
RETURNING id, activity_id, km, pace_s, hr
`

type CreateRunSplitParams struct {
	ActivityID uuid.UUID `json:"activityId"`
	Km         int32     `json:"km"`
	PaceS      int32     `json:"paceS"`
	Hr         int32     `json:"hr"`
}

func (q *Queries) CreateRunSplit(ctx context.Context, arg CreateRunSplitParams) (RunSplit, error) {
	row := q.db.QueryRow(ctx, createRunSplit,
		arg.ActivityID,
		arg.Km,
		arg.PaceS,
		arg.Hr,
	)
	var i RunSplit
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.Km,
		&i.PaceS,
		&i.Hr,
	)
	return i, err
}

const deleteActivity = `-- name: DeleteActivity :exec
DELETE FROM activities WHERE id = $1 AND user_id = $2
`

type DeleteActivityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) DeleteActivity(ctx context.Context, arg DeleteActivityParams) error {
	_, err := q.db.Exec(ctx, deleteActivity, arg.ID, arg.UserID)
	return err
}

const getActivity = `-- name: GetActivity :one
SELECT id, user_id, kind, title, performed_at, load, planned, notes, created_at, updated_at FROM activities WHERE id = $1 AND user_id = $2
`

type GetActivityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) GetActivity(ctx context.Context, arg GetActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivity, arg.ID, arg.UserID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.PerformedAt,
		&i.Load,
		&i.Planned,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunDetail = `-- name: GetRunDetail :one
SELECT activity_id, distance_m, duration_s, avg_pace_s_per_km, avg_hr, calories FROM run_details WHERE activity_id = $1
`

func (q *Queries) GetRunDetail(ctx context.Context, activityID uuid.UUID) (RunDetail, error) {
	row := q.db.QueryRow(ctx, getRunDetail, activityID)
	var i RunDetail
	err := row.Scan(
		&i.ActivityID,
		&i.DistanceM,
		&i.DurationS,
		&i.AvgPaceSPerKm,
		&i.AvgHr,
		&i.Calories,
	)
	return i, err
}

const liftSummary = `-- name: LiftSummary :one
SELECT
    COALESCE(COUNT(ls.id), 0)::bigint                       AS total_sets,
    COALESCE(SUM(ls.weight_kg * ls.reps), 0)::bigint        AS total_volume_kg
FROM exercises e
LEFT JOIN lift_sets ls ON ls.exercise_id = e.id
WHERE e.activity_id = $1
`

type LiftSummaryRow struct {
	TotalSets     int64 `json:"totalSets"`
	TotalVolumeKg int64 `json:"totalVolumeKg"`
}

func (q *Queries) LiftSummary(ctx context.Context, activityID uuid.UUID) (LiftSummaryRow, error) {
	row := q.db.QueryRow(ctx, liftSummary, activityID)
	var i LiftSummaryRow
	err := row.Scan(&i.TotalSets, &i.TotalVolumeKg)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT id, user_id, kind, title, performed_at, load, planned, notes, created_at, updated_at FROM activities
WHERE user_id = $1
  AND ($2::text IS NULL OR kind = $2::text)
ORDER BY performed_at DESC
LIMIT $4 OFFSET $3
`

type ListActivitiesParams struct {
	UserID uuid.UUID `json:"userId"`
	Kind   *string   `json:"kind"`
	Off    int32     `json:"off"`
	Lim    int32     `json:"lim"`
}

func (q *Queries) ListActivities(ctx context.Context, arg ListActivitiesParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivities,
		arg.UserID,
		arg.Kind,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.PerformedAt,
			&i.Load,
			&i.Planned,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesByActivity = `-- name: ListExercisesByActivity :many
SELECT id, activity_id, name, note, position FROM exercises WHERE activity_id = $1 ORDER BY position
`

func (q *Queries) ListExercisesByActivity(ctx context.Context, activityID uuid.UUID) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercisesByActivity, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.Name,
			&i.Note,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiftSetsByExercise = `-- name: ListLiftSetsByExercise :many
SELECT id, exercise_id, weight_kg, reps, done, position FROM lift_sets WHERE exercise_id = $1 ORDER BY position
`

func (q *Queries) ListLiftSetsByExercise(ctx context.Context, exerciseID uuid.UUID) ([]LiftSet, error) {
	rows, err := q.db.Query(ctx, listLiftSetsByExercise, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LiftSet{}
	for rows.Next() {
		var i LiftSet
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.WeightKg,
			&i.Reps,
			&i.Done,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSplits = `-- name: ListRunSplits :many
SELECT id, activity_id, km, pace_s, hr FROM run_splits WHERE activity_id = $1 ORDER BY km
`

func (q *Queries) ListRunSplits(ctx context.Context, activityID uuid.UUID) ([]RunSplit, error) {
	rows, err := q.db.Query(ctx, listRunSplits, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunSplit{}
	for rows.Next() {
		var i RunSplit
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.Km,
			&i.PaceS,
			&i.Hr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadByDayInRange = `-- name: LoadByDayInRange :many
SELECT performed_at::date AS day, COALESCE(SUM(load), 0)::bigint AS load
FROM activities
WHERE user_id = $1 AND planned = false
  AND performed_at >= $2 AND performed_at < $3
GROUP BY day
ORDER BY day
`

type LoadByDayInRangeParams struct {
	UserID uuid.UUID          `json:"userId"`
	Start  pgtype.Timestamptz `json:"start"`
	Stop   pgtype.Timestamptz `json:"stop"`
}

type LoadByDayInRangeRow struct {
	Day  pgtype.Date `json:"day"`
	Load int64       `json:"load"`
}

func (q *Queries) LoadByDayInRange(ctx context.Context, arg LoadByDayInRangeParams) ([]LoadByDayInRangeRow, error) {
	rows, err := q.db.Query(ctx, loadByDayInRange, arg.UserID, arg.Start, arg.Stop)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadByDayInRangeRow{}
	for rows.Next() {
		var i LoadByDayInRangeRow
		if err := rows.Scan(&i.Day, &i.Load); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadByKindInRange = `-- name: LoadByKindInRange :many
SELECT kind, COALESCE(SUM(load), 0)::bigint AS load
FROM activities
WHERE user_id = $1 AND planned = false
  AND performed_at >= $2 AND performed_at < $3
GROUP BY kind
`

type LoadByKindInRangeParams struct {
	UserID uuid.UUID          `json:"userId"`
	Start  pgtype.Timestamptz `json:"start"`
	Stop   pgtype.Timestamptz `json:"stop"`
}

type LoadByKindInRangeRow struct {
	Kind string `json:"kind"`
	Load int64  `json:"load"`
}

func (q *Queries) LoadByKindInRange(ctx context.Context, arg LoadByKindInRangeParams) ([]LoadByKindInRangeRow, error) {
	rows, err := q.db.Query(ctx, loadByKindInRange, arg.UserID, arg.Start, arg.Stop)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadByKindInRangeRow{}
	for rows.Next() {
		var i LoadByKindInRangeRow
		if err := rows.Scan(&i.Kind, &i.Load); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyDistance = `-- name: MonthlyDistance :one
SELECT COALESCE(SUM(rd.distance_m), 0)::bigint AS distance_m
FROM activities a
JOIN run_details rd ON rd.activity_id = a.id
WHERE a.user_id = $1 AND a.performed_at >= $2 AND a.performed_at < $3
`

type MonthlyDistanceParams struct {
	UserID uuid.UUID          `json:"userId"`
	Start  pgtype.Timestamptz `json:"start"`
	Stop   pgtype.Timestamptz `json:"stop"`
}

func (q *Queries) MonthlyDistance(ctx context.Context, arg MonthlyDistanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, monthlyDistance, arg.UserID, arg.Start, arg.Stop)
	var distance_m int64
	err := row.Scan(&distance_m)
	return distance_m, err
}

const monthlyVolume = `-- name: MonthlyVolume :one
SELECT COALESCE(SUM(ls.weight_kg * ls.reps), 0)::bigint AS volume_kg
FROM activities a
JOIN exercises e ON e.activity_id = a.id
JOIN lift_sets ls ON ls.exercise_id = e.id
WHERE a.user_id = $1 AND a.performed_at >= $2 AND a.performed_at < $3
`

type MonthlyVolumeParams struct {
	UserID uuid.UUID          `json:"userId"`
	Start  pgtype.Timestamptz `json:"start"`
	Stop   pgtype.Timestamptz `json:"stop"`
}

func (q *Queries) MonthlyVolume(ctx context.Context, arg MonthlyVolumeParams) (int64, error) {
	row := q.db.QueryRow(ctx, monthlyVolume, arg.UserID, arg.Start, arg.Stop)
	var volume_kg int64
	err := row.Scan(&volume_kg)
	return volume_kg, err
}

const sumLoadInRange = `-- name: SumLoadInRange :one
SELECT COALESCE(SUM(load), 0)::bigint AS load
FROM activities
WHERE user_id = $1 AND planned = false
  AND performed_at >= $2 AND performed_at < $3
`

type SumLoadInRangeParams struct {
	UserID uuid.UUID          `json:"userId"`
	Start  pgtype.Timestamptz `json:"start"`
	Stop   pgtype.Timestamptz `json:"stop"`
}

// ── Training-load rollups ───────────────────────────────────────────────────
func (q *Queries) SumLoadInRange(ctx context.Context, arg SumLoadInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumLoadInRange, arg.UserID, arg.Start, arg.Stop)
	var load int64
	err := row.Scan(&load)
	return load, err
}

const weeklyLoadTrend = `-- name: WeeklyLoadTrend :many
SELECT date_trunc('week', performed_at)::date AS week, COALESCE(SUM(load), 0)::bigint AS load
FROM activities
WHERE user_id = $1 AND planned = false AND performed_at >= $2
GROUP BY week
ORDER BY week
`

type WeeklyLoadTrendParams struct {
	UserID uuid.UUID          `json:"userId"`
	Start  pgtype.Timestamptz `json:"start"`
}

type WeeklyLoadTrendRow struct {
	Week pgtype.Date `json:"week"`
	Load int64       `json:"load"`
}

func (q *Queries) WeeklyLoadTrend(ctx context.Context, arg WeeklyLoadTrendParams) ([]WeeklyLoadTrendRow, error) {
	rows, err := q.db.Query(ctx, weeklyLoadTrend, arg.UserID, arg.Start)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeeklyLoadTrendRow{}
	for rows.Next() {
		var i WeeklyLoadTrendRow
		if err := rows.Scan(&i.Week, &i.Load); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
