// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOTP = `-- name: ConsumeOTP :exec
UPDATE otp_codes SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeOTP, id)
	return err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (user_id, code_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, code_hash, purpose, attempts, expires_at, consumed_at, created_at
`

type CreateOTPParams struct {
	UserID    uuid.UUID          `json:"userId"`
	CodeHash  string             `json:"codeHash"`
	Purpose   string             `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.UserID,
		arg.CodeHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO refresh_sessions (user_id, token_hash, user_agent, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, user_agent, expires_at, revoked_at, created_at
`

type CreateRefreshSessionParams struct {
	UserID    uuid.UUID          `json:"userId"`
	TokenHash string             `json:"tokenHash"`
	UserAgent string             `json:"userAgent"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveOTP = `-- name: GetActiveOTP :one
SELECT id, user_id, code_hash, purpose, attempts, expires_at, consumed_at, created_at FROM otp_codes
WHERE user_id = $1 AND purpose = $2 AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveOTPParams struct {
	UserID  uuid.UUID `json:"userId"`
	Purpose string    `json:"purpose"`
}

func (q *Queries) GetActiveOTP(ctx context.Context, arg GetActiveOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getActiveOTP, arg.UserID, arg.Purpose)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshSession = `-- name: GetRefreshSession :one
SELECT id, user_id, token_hash, user_agent, expires_at, revoked_at, created_at FROM refresh_sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetRefreshSession(ctx context.Context, tokenHash string) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSession, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const invalidateUserOTPs = `-- name: InvalidateUserOTPs :exec
UPDATE otp_codes SET consumed_at = now()
WHERE user_id = $1 AND purpose = $2 AND consumed_at IS NULL
`

type InvalidateUserOTPsParams struct {
	UserID  uuid.UUID `json:"userId"`
	Purpose string    `json:"purpose"`
}

func (q *Queries) InvalidateUserOTPs(ctx context.Context, arg InvalidateUserOTPsParams) error {
	_, err := q.db.Exec(ctx, invalidateUserOTPs, arg.UserID, arg.Purpose)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE refresh_sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeRefreshSession = `-- name: RevokeRefreshSession :exec
UPDATE refresh_sessions SET revoked_at = now() WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshSession, tokenHash)
	return err
}
