// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package store

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertFood = `-- name: UpsertFood :batchexec
INSERT INTO foods (name, serving, kcal, protein_g, carbs_g, fat_g, barcode)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (lower(name)) DO UPDATE SET
    serving   = EXCLUDED.serving,
    kcal      = EXCLUDED.kcal,
    protein_g = EXCLUDED.protein_g,
    carbs_g   = EXCLUDED.carbs_g,
    fat_g     = EXCLUDED.fat_g,
    barcode   = COALESCE(EXCLUDED.barcode, foods.barcode)
`

type UpsertFoodBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertFoodParams struct {
	Name     string         `json:"name"`
	Serving  string         `json:"serving"`
	Kcal     int32          `json:"kcal"`
	ProteinG pgtype.Numeric `json:"proteinG"`
	CarbsG   pgtype.Numeric `json:"carbsG"`
	FatG     pgtype.Numeric `json:"fatG"`
	Barcode  *string        `json:"barcode"`
}

// Idempotent catalogue insert keyed on lower(name) (see idx_foods_lower_name).
func (q *Queries) UpsertFood(ctx context.Context, arg []UpsertFoodParams) *UpsertFoodBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Name,
			a.Serving,
			a.Kcal,
			a.ProteinG,
			a.CarbsG,
			a.FatG,
			a.Barcode,
		}
		batch.Queue(upsertFood, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertFoodBatchResults{br, len(arg), false}
}

func (b *UpsertFoodBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertFoodBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
