// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercise_library.sql

package store

import (
	"context"
)

const listExerciseLibrary = `-- name: ListExerciseLibrary :many
SELECT id, name, muscle, equipment, position FROM exercise_library ORDER BY muscle, position, name
`

func (q *Queries) ListExerciseLibrary(ctx context.Context) ([]ExerciseLibrary, error) {
	rows, err := q.db.Query(ctx, listExerciseLibrary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseLibrary{}
	for rows.Next() {
		var i ExerciseLibrary
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Muscle,
			&i.Equipment,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
