// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foods.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFoods = `-- name: CountFoods :one
SELECT COUNT(*)::bigint AS count FROM foods
`

func (q *Queries) CountFoods(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFoods)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFood = `-- name: CreateFood :one
INSERT INTO foods (name, serving, kcal, protein_g, carbs_g, fat_g, barcode)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, serving, kcal, protein_g, carbs_g, fat_g, barcode, created_at
`

type CreateFoodParams struct {
	Name     string         `json:"name"`
	Serving  string         `json:"serving"`
	Kcal     int32          `json:"kcal"`
	ProteinG pgtype.Numeric `json:"proteinG"`
	CarbsG   pgtype.Numeric `json:"carbsG"`
	FatG     pgtype.Numeric `json:"fatG"`
	Barcode  *string        `json:"barcode"`
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.Name,
		arg.Serving,
		arg.Kcal,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.Barcode,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Serving,
		&i.Kcal,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.Barcode,
		&i.CreatedAt,
	)
	return i, err
}

const getFoodByBarcode = `-- name: GetFoodByBarcode :one
SELECT id, name, serving, kcal, protein_g, carbs_g, fat_g, barcode, created_at FROM foods WHERE barcode = $1
`

func (q *Queries) GetFoodByBarcode(ctx context.Context, barcode *string) (Food, error) {
	row := q.db.QueryRow(ctx, getFoodByBarcode, barcode)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Serving,
		&i.Kcal,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.Barcode,
		&i.CreatedAt,
	)
	return i, err
}

const searchFoods = `-- name: SearchFoods :many
SELECT id, name, serving, kcal, protein_g, carbs_g, fat_g, barcode, created_at FROM foods
WHERE name ILIKE ALL (
        SELECT '%' || w || '%'
        FROM unnest(string_to_array(lower(btrim($1::text)), ' ')) AS w
        WHERE w <> ''
    )
ORDER BY
    (name ILIKE $1::text || '%') DESC,  -- whole-query prefix first
    length(name),
    name
LIMIT $2
`

type SearchFoodsParams struct {
	Query string `json:"query"`
	Lim   int32  `json:"lim"`
}

// Word-order-independent: every whitespace-separated token in the query must
// appear somewhere in the name, so "greek yogurt" matches "Yogurt, Greek, plain".
// Shorter names rank higher (less qualified = more likely what the user meant).
// The caller must reject an empty query (ILIKE ALL over an empty set is TRUE).
func (q *Queries) SearchFoods(ctx context.Context, arg SearchFoodsParams) ([]Food, error) {
	rows, err := q.db.Query(ctx, searchFoods, arg.Query, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Food{}
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Serving,
			&i.Kcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.Barcode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
