// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"userId"`
	Kind        string             `json:"kind"`
	Title       string             `json:"title"`
	PerformedAt pgtype.Timestamptz `json:"performedAt"`
	Load        int32              `json:"load"`
	Planned     bool               `json:"planned"`
	Notes       string             `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type Exercise struct {
	ID         uuid.UUID `json:"id"`
	ActivityID uuid.UUID `json:"activityId"`
	Name       string    `json:"name"`
	Note       string    `json:"note"`
	Position   int32     `json:"position"`
}

type ExerciseLibrary struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	Muscle           string    `json:"muscle"`
	Equipment        string    `json:"equipment"`
	Position         int32     `json:"position"`
	ExternalID       int32     `json:"externalId"`
	Difficulty       string    `json:"difficulty"`
	Force            string    `json:"force"`
	Grips            string    `json:"grips"`
	SecondaryMuscles []byte    `json:"secondaryMuscles"`
	Steps            []byte    `json:"steps"`
	VideoUrls        []byte    `json:"videoUrls"`
	YoutubeUrl       string    `json:"youtubeUrl"`
	Details          string    `json:"details"`
}

type Food struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Serving   string             `json:"serving"`
	Kcal      int32              `json:"kcal"`
	ProteinG  pgtype.Numeric     `json:"proteinG"`
	CarbsG    pgtype.Numeric     `json:"carbsG"`
	FatG      pgtype.Numeric     `json:"fatG"`
	Barcode   *string            `json:"barcode"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type LiftSet struct {
	ID         uuid.UUID      `json:"id"`
	ExerciseID uuid.UUID      `json:"exerciseId"`
	WeightKg   pgtype.Numeric `json:"weightKg"`
	Reps       int32          `json:"reps"`
	Done       bool           `json:"done"`
	Position   int32          `json:"position"`
}

type Meal struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"userId"`
	Day       pgtype.Date        `json:"day"`
	Slot      string             `json:"slot"`
	LoggedAt  pgtype.Timestamptz `json:"loggedAt"`
	Planned   bool               `json:"planned"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type MealItem struct {
	ID       uuid.UUID      `json:"id"`
	MealID   uuid.UUID      `json:"mealId"`
	Name     string         `json:"name"`
	Kcal     int32          `json:"kcal"`
	ProteinG pgtype.Numeric `json:"proteinG"`
	CarbsG   pgtype.Numeric `json:"carbsG"`
	FatG     pgtype.Numeric `json:"fatG"`
	Position int32          `json:"position"`
}

type NutritionDay struct {
	ID                uuid.UUID   `json:"id"`
	UserID            uuid.UUID   `json:"userId"`
	Day               pgtype.Date `json:"day"`
	BaseKcal          int32       `json:"baseKcal"`
	TrainingBonusKcal int32       `json:"trainingBonusKcal"`
	WaterMl           int32       `json:"waterMl"`
	WaterTargetMl     int32       `json:"waterTargetMl"`
	ProteinTargetG    int32       `json:"proteinTargetG"`
	CarbsTargetG      int32       `json:"carbsTargetG"`
	FatTargetG        int32       `json:"fatTargetG"`
}

type OtpCode struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"userId"`
	CodeHash   string             `json:"codeHash"`
	Purpose    string             `json:"purpose"`
	Attempts   int32              `json:"attempts"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	ConsumedAt pgtype.Timestamptz `json:"consumedAt"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type PersonalRecord struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"userId"`
	Label    string    `json:"label"`
	Value    string    `json:"value"`
	Icon     string    `json:"icon"`
	Position int32     `json:"position"`
}

type PlanItem struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"userId"`
	PlanDate  pgtype.Date        `json:"planDate"`
	Kind      string             `json:"kind"`
	Title     string             `json:"title"`
	Meta      string             `json:"meta"`
	Done      bool               `json:"done"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type RefreshSession struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"userId"`
	TokenHash string             `json:"tokenHash"`
	UserAgent string             `json:"userAgent"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	RevokedAt pgtype.Timestamptz `json:"revokedAt"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type RunDetail struct {
	ActivityID    uuid.UUID `json:"activityId"`
	DistanceM     int32     `json:"distanceM"`
	DurationS     int32     `json:"durationS"`
	AvgPaceSPerKm int32     `json:"avgPaceSPerKm"`
	AvgHr         int32     `json:"avgHr"`
	Calories      int32     `json:"calories"`
	Route         []byte    `json:"route"`
}

type RunSplit struct {
	ID         uuid.UUID `json:"id"`
	ActivityID uuid.UUID `json:"activityId"`
	Km         int32     `json:"km"`
	PaceS      int32     `json:"paceS"`
	Hr         int32     `json:"hr"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	PasswordHash  *string            `json:"passwordHash"`
	EmailVerified bool               `json:"emailVerified"`
	Handle        string             `json:"handle"`
	Status        string             `json:"status"`
	Streak        int32              `json:"streak"`
	LoadTarget    int32              `json:"loadTarget"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type UserSetting struct {
	UserID        uuid.UUID          `json:"userId"`
	Units         string             `json:"units"`
	Notifications bool               `json:"notifications"`
	ConnectedApps int32              `json:"connectedApps"`
	BodyWeightKg  pgtype.Numeric     `json:"bodyWeightKg"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}
