// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deletePushToken = `-- name: DeletePushToken :exec
DELETE FROM push_tokens WHERE token = $1 AND user_id = $2
`

type DeletePushTokenParams struct {
	Token  string    `json:"token"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error {
	_, err := q.db.Exec(ctx, deletePushToken, arg.Token, arg.UserID)
	return err
}

const deletePushTokenByValue = `-- name: DeletePushTokenByValue :exec
DELETE FROM push_tokens WHERE token = $1
`

// Used by the sender to drop tokens Expo reports as DeviceNotRegistered.
func (q *Queries) DeletePushTokenByValue(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deletePushTokenByValue, token)
	return err
}

const getNotificationPrefs = `-- name: GetNotificationPrefs :one
SELECT notification_prefs FROM user_settings WHERE user_id = $1
`

func (q *Queries) GetNotificationPrefs(ctx context.Context, userID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getNotificationPrefs, userID)
	var notification_prefs []byte
	err := row.Scan(&notification_prefs)
	return notification_prefs, err
}

const listUserPushTokens = `-- name: ListUserPushTokens :many
SELECT id, user_id, token, platform, created_at, updated_at FROM push_tokens WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListUserPushTokens(ctx context.Context, userID uuid.UUID) ([]PushToken, error) {
	rows, err := q.db.Query(ctx, listUserPushTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushToken{}
	for rows.Next() {
		var i PushToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationPrefs = `-- name: UpdateNotificationPrefs :one
UPDATE user_settings SET notification_prefs = $2, updated_at = now()
WHERE user_id = $1
RETURNING notification_prefs
`

type UpdateNotificationPrefsParams struct {
	UserID            uuid.UUID `json:"userId"`
	NotificationPrefs []byte    `json:"notificationPrefs"`
}

func (q *Queries) UpdateNotificationPrefs(ctx context.Context, arg UpdateNotificationPrefsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, updateNotificationPrefs, arg.UserID, arg.NotificationPrefs)
	var notification_prefs []byte
	err := row.Scan(&notification_prefs)
	return notification_prefs, err
}

const upsertPushToken = `-- name: UpsertPushToken :exec
INSERT INTO push_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE SET
    user_id    = EXCLUDED.user_id,
    platform   = EXCLUDED.platform,
    updated_at = now()
`

type UpsertPushTokenParams struct {
	UserID   uuid.UUID `json:"userId"`
	Token    string    `json:"token"`
	Platform string    `json:"platform"`
}

// Register a device's push token to a user; re-owns the device on conflict.
func (q *Queries) UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) error {
	_, err := q.db.Exec(ctx, upsertPushToken, arg.UserID, arg.Token, arg.Platform)
	return err
}
