// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nutrition.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addWater = `-- name: AddWater :one
INSERT INTO nutrition_days (user_id, day, water_ml)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, day)
DO UPDATE SET water_ml = GREATEST(0, nutrition_days.water_ml + EXCLUDED.water_ml)
RETURNING id, user_id, day, base_kcal, training_bonus_kcal, water_ml, water_target_ml, protein_target_g, carbs_target_g, fat_target_g
`

type AddWaterParams struct {
	UserID  uuid.UUID   `json:"userId"`
	Day     pgtype.Date `json:"day"`
	DeltaMl int32       `json:"deltaMl"`
}

func (q *Queries) AddWater(ctx context.Context, arg AddWaterParams) (NutritionDay, error) {
	row := q.db.QueryRow(ctx, addWater, arg.UserID, arg.Day, arg.DeltaMl)
	var i NutritionDay
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.BaseKcal,
		&i.TrainingBonusKcal,
		&i.WaterMl,
		&i.WaterTargetMl,
		&i.ProteinTargetG,
		&i.CarbsTargetG,
		&i.FatTargetG,
	)
	return i, err
}

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (user_id, day, slot, logged_at, planned, position)
VALUES ($1, $6, $2, $3, $4, $5)
RETURNING id, user_id, day, slot, logged_at, planned, position, created_at
`

type CreateMealParams struct {
	UserID   uuid.UUID          `json:"userId"`
	Slot     string             `json:"slot"`
	LoggedAt pgtype.Timestamptz `json:"loggedAt"`
	Planned  bool               `json:"planned"`
	Position int32              `json:"position"`
	Day      pgtype.Date        `json:"day"`
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal,
		arg.UserID,
		arg.Slot,
		arg.LoggedAt,
		arg.Planned,
		arg.Position,
		arg.Day,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.Slot,
		&i.LoggedAt,
		&i.Planned,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createMealItem = `-- name: CreateMealItem :one
INSERT INTO meal_items (meal_id, name, kcal, protein_g, carbs_g, fat_g, position)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, meal_id, name, kcal, protein_g, carbs_g, fat_g, position
`

type CreateMealItemParams struct {
	MealID   uuid.UUID      `json:"mealId"`
	Name     string         `json:"name"`
	Kcal     int32          `json:"kcal"`
	ProteinG pgtype.Numeric `json:"proteinG"`
	CarbsG   pgtype.Numeric `json:"carbsG"`
	FatG     pgtype.Numeric `json:"fatG"`
	Position int32          `json:"position"`
}

func (q *Queries) CreateMealItem(ctx context.Context, arg CreateMealItemParams) (MealItem, error) {
	row := q.db.QueryRow(ctx, createMealItem,
		arg.MealID,
		arg.Name,
		arg.Kcal,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.Position,
	)
	var i MealItem
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.Name,
		&i.Kcal,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.Position,
	)
	return i, err
}

const dayConsumed = `-- name: DayConsumed :one
SELECT
    COALESCE(SUM(mi.kcal), 0)::bigint     AS kcal,
    COALESCE(SUM(mi.protein_g), 0)::float8 AS protein_g,
    COALESCE(SUM(mi.carbs_g), 0)::float8   AS carbs_g,
    COALESCE(SUM(mi.fat_g), 0)::float8     AS fat_g
FROM meals m
JOIN meal_items mi ON mi.meal_id = m.id
WHERE m.user_id = $1 AND m.day = $2
`

type DayConsumedParams struct {
	UserID uuid.UUID   `json:"userId"`
	Day    pgtype.Date `json:"day"`
}

type DayConsumedRow struct {
	Kcal     int64   `json:"kcal"`
	ProteinG float64 `json:"proteinG"`
	CarbsG   float64 `json:"carbsG"`
	FatG     float64 `json:"fatG"`
}

func (q *Queries) DayConsumed(ctx context.Context, arg DayConsumedParams) (DayConsumedRow, error) {
	row := q.db.QueryRow(ctx, dayConsumed, arg.UserID, arg.Day)
	var i DayConsumedRow
	err := row.Scan(
		&i.Kcal,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals WHERE id = $1 AND user_id = $2
`

type DeleteMealParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) DeleteMeal(ctx context.Context, arg DeleteMealParams) error {
	_, err := q.db.Exec(ctx, deleteMeal, arg.ID, arg.UserID)
	return err
}

const getNutritionDay = `-- name: GetNutritionDay :one
SELECT id, user_id, day, base_kcal, training_bonus_kcal, water_ml, water_target_ml, protein_target_g, carbs_target_g, fat_target_g FROM nutrition_days WHERE user_id = $1 AND day = $2
`

type GetNutritionDayParams struct {
	UserID uuid.UUID   `json:"userId"`
	Day    pgtype.Date `json:"day"`
}

func (q *Queries) GetNutritionDay(ctx context.Context, arg GetNutritionDayParams) (NutritionDay, error) {
	row := q.db.QueryRow(ctx, getNutritionDay, arg.UserID, arg.Day)
	var i NutritionDay
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.BaseKcal,
		&i.TrainingBonusKcal,
		&i.WaterMl,
		&i.WaterTargetMl,
		&i.ProteinTargetG,
		&i.CarbsTargetG,
		&i.FatTargetG,
	)
	return i, err
}

const listMealItems = `-- name: ListMealItems :many
SELECT id, meal_id, name, kcal, protein_g, carbs_g, fat_g, position FROM meal_items WHERE meal_id = $1 ORDER BY position
`

func (q *Queries) ListMealItems(ctx context.Context, mealID uuid.UUID) ([]MealItem, error) {
	rows, err := q.db.Query(ctx, listMealItems, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealItem{}
	for rows.Next() {
		var i MealItem
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.Name,
			&i.Kcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealItemsForDay = `-- name: ListMealItemsForDay :many
SELECT mi.id, mi.meal_id, mi.name, mi.kcal, mi.protein_g, mi.carbs_g, mi.fat_g, mi.position FROM meal_items mi
JOIN meals m ON m.id = mi.meal_id
WHERE m.user_id = $1 AND m.day = $2
ORDER BY mi.meal_id, mi.position
`

type ListMealItemsForDayParams struct {
	UserID uuid.UUID   `json:"userId"`
	Day    pgtype.Date `json:"day"`
}

func (q *Queries) ListMealItemsForDay(ctx context.Context, arg ListMealItemsForDayParams) ([]MealItem, error) {
	rows, err := q.db.Query(ctx, listMealItemsForDay, arg.UserID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealItem{}
	for rows.Next() {
		var i MealItem
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.Name,
			&i.Kcal,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsForDay = `-- name: ListMealsForDay :many
SELECT id, user_id, day, slot, logged_at, planned, position, created_at FROM meals
WHERE user_id = $1 AND day = $2
ORDER BY position, created_at
`

type ListMealsForDayParams struct {
	UserID uuid.UUID   `json:"userId"`
	Day    pgtype.Date `json:"day"`
}

func (q *Queries) ListMealsForDay(ctx context.Context, arg ListMealsForDayParams) ([]Meal, error) {
	rows, err := q.db.Query(ctx, listMealsForDay, arg.UserID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Day,
			&i.Slot,
			&i.LoggedAt,
			&i.Planned,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mealOwnedBy = `-- name: MealOwnedBy :one
SELECT EXISTS (SELECT 1 FROM meals WHERE id = $1 AND user_id = $2) AS owned
`

type MealOwnedByParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) MealOwnedBy(ctx context.Context, arg MealOwnedByParams) (bool, error) {
	row := q.db.QueryRow(ctx, mealOwnedBy, arg.ID, arg.UserID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const sumCaloriesInRange = `-- name: SumCaloriesInRange :one
SELECT COALESCE(SUM(mi.kcal), 0)::bigint AS kcal
FROM meals m
JOIN meal_items mi ON mi.meal_id = m.id
WHERE m.user_id = $1 AND m.day >= $2 AND m.day < $3
`

type SumCaloriesInRangeParams struct {
	UserID uuid.UUID   `json:"userId"`
	Start  pgtype.Date `json:"start"`
	Stop   pgtype.Date `json:"stop"`
}

func (q *Queries) SumCaloriesInRange(ctx context.Context, arg SumCaloriesInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumCaloriesInRange, arg.UserID, arg.Start, arg.Stop)
	var kcal int64
	err := row.Scan(&kcal)
	return kcal, err
}

const upsertNutritionDay = `-- name: UpsertNutritionDay :one
INSERT INTO nutrition_days (user_id, day)
VALUES ($1, $2)
ON CONFLICT (user_id, day) DO UPDATE SET day = EXCLUDED.day
RETURNING id, user_id, day, base_kcal, training_bonus_kcal, water_ml, water_target_ml, protein_target_g, carbs_target_g, fat_target_g
`

type UpsertNutritionDayParams struct {
	UserID uuid.UUID   `json:"userId"`
	Day    pgtype.Date `json:"day"`
}

func (q *Queries) UpsertNutritionDay(ctx context.Context, arg UpsertNutritionDayParams) (NutritionDay, error) {
	row := q.db.QueryRow(ctx, upsertNutritionDay, arg.UserID, arg.Day)
	var i NutritionDay
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Day,
		&i.BaseKcal,
		&i.TrainingBonusKcal,
		&i.WaterMl,
		&i.WaterTargetMl,
		&i.ProteinTargetG,
		&i.CarbsTargetG,
		&i.FatTargetG,
	)
	return i, err
}
