// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlanItem = `-- name: CreatePlanItem :one
INSERT INTO plan_items (user_id, plan_date, kind, title, meta, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, plan_date, kind, title, meta, done, position, created_at
`

type CreatePlanItemParams struct {
	UserID   uuid.UUID   `json:"userId"`
	PlanDate pgtype.Date `json:"planDate"`
	Kind     string      `json:"kind"`
	Title    string      `json:"title"`
	Meta     string      `json:"meta"`
	Position int32       `json:"position"`
}

func (q *Queries) CreatePlanItem(ctx context.Context, arg CreatePlanItemParams) (PlanItem, error) {
	row := q.db.QueryRow(ctx, createPlanItem,
		arg.UserID,
		arg.PlanDate,
		arg.Kind,
		arg.Title,
		arg.Meta,
		arg.Position,
	)
	var i PlanItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.Kind,
		&i.Title,
		&i.Meta,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlanItem = `-- name: DeletePlanItem :exec
DELETE FROM plan_items WHERE id = $1 AND user_id = $2
`

type DeletePlanItemParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) DeletePlanItem(ctx context.Context, arg DeletePlanItemParams) error {
	_, err := q.db.Exec(ctx, deletePlanItem, arg.ID, arg.UserID)
	return err
}

const listPlanItems = `-- name: ListPlanItems :many
SELECT id, user_id, plan_date, kind, title, meta, done, position, created_at FROM plan_items
WHERE user_id = $1 AND plan_date = $2
ORDER BY position, created_at
`

type ListPlanItemsParams struct {
	UserID   uuid.UUID   `json:"userId"`
	PlanDate pgtype.Date `json:"planDate"`
}

func (q *Queries) ListPlanItems(ctx context.Context, arg ListPlanItemsParams) ([]PlanItem, error) {
	rows, err := q.db.Query(ctx, listPlanItems, arg.UserID, arg.PlanDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanItem{}
	for rows.Next() {
		var i PlanItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanDate,
			&i.Kind,
			&i.Title,
			&i.Meta,
			&i.Done,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlanItemDone = `-- name: SetPlanItemDone :one
UPDATE plan_items SET done = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, plan_date, kind, title, meta, done, position, created_at
`

type SetPlanItemDoneParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
	Done   bool      `json:"done"`
}

func (q *Queries) SetPlanItemDone(ctx context.Context, arg SetPlanItemDoneParams) (PlanItem, error) {
	row := q.db.QueryRow(ctx, setPlanItemDone, arg.ID, arg.UserID, arg.Done)
	var i PlanItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanDate,
		&i.Kind,
		&i.Title,
		&i.Meta,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
