// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prs.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createPersonalRecord = `-- name: CreatePersonalRecord :one
INSERT INTO personal_records (user_id, label, value, icon, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, label, value, icon, position
`

type CreatePersonalRecordParams struct {
	UserID   uuid.UUID `json:"userId"`
	Label    string    `json:"label"`
	Value    string    `json:"value"`
	Icon     string    `json:"icon"`
	Position int32     `json:"position"`
}

func (q *Queries) CreatePersonalRecord(ctx context.Context, arg CreatePersonalRecordParams) (PersonalRecord, error) {
	row := q.db.QueryRow(ctx, createPersonalRecord,
		arg.UserID,
		arg.Label,
		arg.Value,
		arg.Icon,
		arg.Position,
	)
	var i PersonalRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Value,
		&i.Icon,
		&i.Position,
	)
	return i, err
}

const deletePersonalRecord = `-- name: DeletePersonalRecord :exec
DELETE FROM personal_records WHERE id = $1 AND user_id = $2
`

type DeletePersonalRecordParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) DeletePersonalRecord(ctx context.Context, arg DeletePersonalRecordParams) error {
	_, err := q.db.Exec(ctx, deletePersonalRecord, arg.ID, arg.UserID)
	return err
}

const listPersonalRecords = `-- name: ListPersonalRecords :many
SELECT id, user_id, label, value, icon, position FROM personal_records WHERE user_id = $1 ORDER BY position
`

func (q *Queries) ListPersonalRecords(ctx context.Context, userID uuid.UUID) ([]PersonalRecord, error) {
	rows, err := q.db.Query(ctx, listPersonalRecords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonalRecord{}
	for rows.Next() {
		var i PersonalRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.Value,
			&i.Icon,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
