// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddWater(ctx context.Context, arg AddWaterParams) (NutritionDay, error)
	ConsumeOTP(ctx context.Context, id uuid.UUID) error
	CountFoods(ctx context.Context) (int64, error)
	CountSessionsInRange(ctx context.Context, arg CountSessionsInRangeParams) (int64, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	// ── Lift details ────────────────────────────────────────────────────────────
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error)
	CreateLiftSet(ctx context.Context, arg CreateLiftSetParams) (LiftSet, error)
	CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error)
	CreateMealItem(ctx context.Context, arg CreateMealItemParams) (MealItem, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error)
	CreatePersonalRecord(ctx context.Context, arg CreatePersonalRecordParams) (PersonalRecord, error)
	CreatePlanItem(ctx context.Context, arg CreatePlanItemParams) (PlanItem, error)
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error)
	CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error)
	CreateRoutineExercise(ctx context.Context, arg CreateRoutineExerciseParams) (RoutineExercise, error)
	// ── Run details ─────────────────────────────────────────────────────────────
	CreateRunDetail(ctx context.Context, arg CreateRunDetailParams) (RunDetail, error)
	CreateRunSplit(ctx context.Context, arg CreateRunSplitParams) (RunSplit, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error)
	DayConsumed(ctx context.Context, arg DayConsumedParams) (DayConsumedRow, error)
	DeleteActivity(ctx context.Context, arg DeleteActivityParams) error
	DeleteMeal(ctx context.Context, arg DeleteMealParams) error
	DeletePersonalRecord(ctx context.Context, arg DeletePersonalRecordParams) error
	DeletePlanItem(ctx context.Context, arg DeletePlanItemParams) error
	DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error
	// Used by the sender to drop tokens Expo reports as DeviceNotRegistered.
	DeletePushTokenByValue(ctx context.Context, token string) error
	DeleteRoutine(ctx context.Context, arg DeleteRoutineParams) error
	DeleteRoutineExercises(ctx context.Context, routineID uuid.UUID) error
	GetActiveOTP(ctx context.Context, arg GetActiveOTPParams) (OtpCode, error)
	GetActivity(ctx context.Context, arg GetActivityParams) (Activity, error)
	// Consecutive days (ending today or yesterday, UTC) with >=1 logged activity.
	// Gaps-and-islands: consecutive dates share (date - row_number) as a group key;
	// the streak is the run that reaches today or yesterday, else 0.
	GetActivityStreak(ctx context.Context, userID uuid.UUID) (int32, error)
	GetFoodByBarcode(ctx context.Context, barcode *string) (Food, error)
	GetNotificationPrefs(ctx context.Context, userID uuid.UUID) ([]byte, error)
	GetNutritionDay(ctx context.Context, arg GetNutritionDayParams) (NutritionDay, error)
	GetRefreshSession(ctx context.Context, tokenHash string) (RefreshSession, error)
	GetRoutine(ctx context.Context, arg GetRoutineParams) (Routine, error)
	GetRunDetail(ctx context.Context, activityID uuid.UUID) (RunDetail, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error)
	IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error
	InvalidateUserOTPs(ctx context.Context, arg InvalidateUserOTPsParams) error
	LiftSummary(ctx context.Context, activityID uuid.UUID) (LiftSummaryRow, error)
	ListActivities(ctx context.Context, arg ListActivitiesParams) ([]Activity, error)
	ListExerciseLibrary(ctx context.Context) ([]ExerciseLibrary, error)
	ListExercisesByActivity(ctx context.Context, activityID uuid.UUID) ([]Exercise, error)
	ListLiftSetsByExercise(ctx context.Context, exerciseID uuid.UUID) ([]LiftSet, error)
	ListMealItems(ctx context.Context, mealID uuid.UUID) ([]MealItem, error)
	ListMealItemsForDay(ctx context.Context, arg ListMealItemsForDayParams) ([]MealItem, error)
	ListMealsForDay(ctx context.Context, arg ListMealsForDayParams) ([]Meal, error)
	ListPersonalRecords(ctx context.Context, userID uuid.UUID) ([]PersonalRecord, error)
	ListPlanItems(ctx context.Context, arg ListPlanItemsParams) ([]PlanItem, error)
	ListRoutineExercises(ctx context.Context, routineID uuid.UUID) ([]RoutineExercise, error)
	ListRoutines(ctx context.Context, userID uuid.UUID) ([]Routine, error)
	ListRunSplits(ctx context.Context, activityID uuid.UUID) ([]RunSplit, error)
	ListUserPushTokens(ctx context.Context, userID uuid.UUID) ([]PushToken, error)
	LoadByDayInRange(ctx context.Context, arg LoadByDayInRangeParams) ([]LoadByDayInRangeRow, error)
	LoadByKindInRange(ctx context.Context, arg LoadByKindInRangeParams) ([]LoadByKindInRangeRow, error)
	MealOwnedBy(ctx context.Context, arg MealOwnedByParams) (bool, error)
	MonthlyDistance(ctx context.Context, arg MonthlyDistanceParams) (int64, error)
	MonthlyVolume(ctx context.Context, arg MonthlyVolumeParams) (int64, error)
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshSession(ctx context.Context, tokenHash string) error
	// Word-order-independent: every whitespace-separated token in the query must
	// appear somewhere in the name, so "greek yogurt" matches "Yogurt, Greek, plain".
	// Shorter names rank higher (less qualified = more likely what the user meant).
	// The caller must reject an empty query (ILIKE ALL over an empty set is TRUE).
	SearchFoods(ctx context.Context, arg SearchFoodsParams) ([]Food, error)
	SetEmailVerified(ctx context.Context, id uuid.UUID) error
	SetPlanItemDone(ctx context.Context, arg SetPlanItemDoneParams) (PlanItem, error)
	SumCaloriesInRange(ctx context.Context, arg SumCaloriesInRangeParams) (int64, error)
	// ── Training-load rollups ───────────────────────────────────────────────────
	SumLoadInRange(ctx context.Context, arg SumLoadInRangeParams) (int64, error)
	UpdateNotificationPrefs(ctx context.Context, arg UpdateNotificationPrefsParams) ([]byte, error)
	UpdateRoutine(ctx context.Context, arg UpdateRoutineParams) (Routine, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error)
	UpsertExerciseLibrary(ctx context.Context, arg UpsertExerciseLibraryParams) error
	// Idempotent catalogue insert keyed on lower(name) (see idx_foods_lower_name).
	UpsertFood(ctx context.Context, arg []UpsertFoodParams) *UpsertFoodBatchResults
	UpsertNutritionDay(ctx context.Context, arg UpsertNutritionDayParams) (NutritionDay, error)
	// Register a device's push token to a user; re-owns the device on conflict.
	UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) error
	WeeklyLoadTrend(ctx context.Context, arg WeeklyLoadTrendParams) ([]WeeklyLoadTrendRow, error)
}

var _ Querier = (*Queries)(nil)
