// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddWater(ctx context.Context, arg AddWaterParams) (NutritionDay, error)
	ConsumeOTP(ctx context.Context, id uuid.UUID) error
	CountFoods(ctx context.Context) (int64, error)
	CountSessionsInRange(ctx context.Context, arg CountSessionsInRangeParams) (int64, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	// ── Lift details ────────────────────────────────────────────────────────────
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error)
	CreateLiftSet(ctx context.Context, arg CreateLiftSetParams) (LiftSet, error)
	CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error)
	CreateMealItem(ctx context.Context, arg CreateMealItemParams) (MealItem, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error)
	CreatePersonalRecord(ctx context.Context, arg CreatePersonalRecordParams) (PersonalRecord, error)
	CreatePlanItem(ctx context.Context, arg CreatePlanItemParams) (PlanItem, error)
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error)
	// ── Run details ─────────────────────────────────────────────────────────────
	CreateRunDetail(ctx context.Context, arg CreateRunDetailParams) (RunDetail, error)
	CreateRunSplit(ctx context.Context, arg CreateRunSplitParams) (RunSplit, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error)
	DayConsumed(ctx context.Context, arg DayConsumedParams) (DayConsumedRow, error)
	DeleteActivity(ctx context.Context, arg DeleteActivityParams) error
	DeleteMeal(ctx context.Context, arg DeleteMealParams) error
	DeletePersonalRecord(ctx context.Context, arg DeletePersonalRecordParams) error
	DeletePlanItem(ctx context.Context, arg DeletePlanItemParams) error
	GetActiveOTP(ctx context.Context, arg GetActiveOTPParams) (OtpCode, error)
	GetActivity(ctx context.Context, arg GetActivityParams) (Activity, error)
	GetFoodByBarcode(ctx context.Context, barcode *string) (Food, error)
	GetNutritionDay(ctx context.Context, arg GetNutritionDayParams) (NutritionDay, error)
	GetRefreshSession(ctx context.Context, tokenHash string) (RefreshSession, error)
	GetRunDetail(ctx context.Context, activityID uuid.UUID) (RunDetail, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error)
	IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error
	InvalidateUserOTPs(ctx context.Context, arg InvalidateUserOTPsParams) error
	LiftSummary(ctx context.Context, activityID uuid.UUID) (LiftSummaryRow, error)
	ListActivities(ctx context.Context, arg ListActivitiesParams) ([]Activity, error)
	ListExercisesByActivity(ctx context.Context, activityID uuid.UUID) ([]Exercise, error)
	ListLiftSetsByExercise(ctx context.Context, exerciseID uuid.UUID) ([]LiftSet, error)
	ListMealItems(ctx context.Context, mealID uuid.UUID) ([]MealItem, error)
	ListMealItemsForDay(ctx context.Context, arg ListMealItemsForDayParams) ([]MealItem, error)
	ListMealsForDay(ctx context.Context, arg ListMealsForDayParams) ([]Meal, error)
	ListPersonalRecords(ctx context.Context, userID uuid.UUID) ([]PersonalRecord, error)
	ListPlanItems(ctx context.Context, arg ListPlanItemsParams) ([]PlanItem, error)
	ListRunSplits(ctx context.Context, activityID uuid.UUID) ([]RunSplit, error)
	LoadByDayInRange(ctx context.Context, arg LoadByDayInRangeParams) ([]LoadByDayInRangeRow, error)
	LoadByKindInRange(ctx context.Context, arg LoadByKindInRangeParams) ([]LoadByKindInRangeRow, error)
	MealOwnedBy(ctx context.Context, arg MealOwnedByParams) (bool, error)
	MonthlyDistance(ctx context.Context, arg MonthlyDistanceParams) (int64, error)
	MonthlyVolume(ctx context.Context, arg MonthlyVolumeParams) (int64, error)
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshSession(ctx context.Context, tokenHash string) error
	SearchFoods(ctx context.Context, arg SearchFoodsParams) ([]Food, error)
	SetEmailVerified(ctx context.Context, id uuid.UUID) error
	SetPlanItemDone(ctx context.Context, arg SetPlanItemDoneParams) (PlanItem, error)
	SumCaloriesInRange(ctx context.Context, arg SumCaloriesInRangeParams) (int64, error)
	// ── Training-load rollups ───────────────────────────────────────────────────
	SumLoadInRange(ctx context.Context, arg SumLoadInRangeParams) (int64, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error)
	UpsertNutritionDay(ctx context.Context, arg UpsertNutritionDayParams) (NutritionDay, error)
	WeeklyLoadTrend(ctx context.Context, arg WeeklyLoadTrendParams) ([]WeeklyLoadTrendRow, error)
}

var _ Querier = (*Queries)(nil)
