// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routines.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createRoutine = `-- name: CreateRoutine :one
INSERT INTO routines (user_id, name, note, position)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, note, position, created_at, updated_at
`

type CreateRoutineParams struct {
	UserID   uuid.UUID `json:"userId"`
	Name     string    `json:"name"`
	Note     string    `json:"note"`
	Position int32     `json:"position"`
}

func (q *Queries) CreateRoutine(ctx context.Context, arg CreateRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, createRoutine,
		arg.UserID,
		arg.Name,
		arg.Note,
		arg.Position,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoutineExercise = `-- name: CreateRoutineExercise :one
INSERT INTO routine_exercises (routine_id, name, note, target_sets, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, routine_id, name, note, target_sets, position
`

type CreateRoutineExerciseParams struct {
	RoutineID  uuid.UUID `json:"routineId"`
	Name       string    `json:"name"`
	Note       string    `json:"note"`
	TargetSets int32     `json:"targetSets"`
	Position   int32     `json:"position"`
}

func (q *Queries) CreateRoutineExercise(ctx context.Context, arg CreateRoutineExerciseParams) (RoutineExercise, error) {
	row := q.db.QueryRow(ctx, createRoutineExercise,
		arg.RoutineID,
		arg.Name,
		arg.Note,
		arg.TargetSets,
		arg.Position,
	)
	var i RoutineExercise
	err := row.Scan(
		&i.ID,
		&i.RoutineID,
		&i.Name,
		&i.Note,
		&i.TargetSets,
		&i.Position,
	)
	return i, err
}

const deleteRoutine = `-- name: DeleteRoutine :exec
DELETE FROM routines WHERE id = $1 AND user_id = $2
`

type DeleteRoutineParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) DeleteRoutine(ctx context.Context, arg DeleteRoutineParams) error {
	_, err := q.db.Exec(ctx, deleteRoutine, arg.ID, arg.UserID)
	return err
}

const deleteRoutineExercises = `-- name: DeleteRoutineExercises :exec
DELETE FROM routine_exercises WHERE routine_id = $1
`

func (q *Queries) DeleteRoutineExercises(ctx context.Context, routineID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoutineExercises, routineID)
	return err
}

const getRoutine = `-- name: GetRoutine :one
SELECT id, user_id, name, note, position, created_at, updated_at FROM routines WHERE id = $1 AND user_id = $2
`

type GetRoutineParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) GetRoutine(ctx context.Context, arg GetRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, getRoutine, arg.ID, arg.UserID)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoutineExercises = `-- name: ListRoutineExercises :many
SELECT id, routine_id, name, note, target_sets, position FROM routine_exercises WHERE routine_id = $1 ORDER BY position
`

func (q *Queries) ListRoutineExercises(ctx context.Context, routineID uuid.UUID) ([]RoutineExercise, error) {
	rows, err := q.db.Query(ctx, listRoutineExercises, routineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutineExercise{}
	for rows.Next() {
		var i RoutineExercise
		if err := rows.Scan(
			&i.ID,
			&i.RoutineID,
			&i.Name,
			&i.Note,
			&i.TargetSets,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutines = `-- name: ListRoutines :many
SELECT id, user_id, name, note, position, created_at, updated_at FROM routines WHERE user_id = $1 ORDER BY position, created_at
`

func (q *Queries) ListRoutines(ctx context.Context, userID uuid.UUID) ([]Routine, error) {
	rows, err := q.db.Query(ctx, listRoutines, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Routine{}
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Note,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoutine = `-- name: UpdateRoutine :one
UPDATE routines SET name = $3, note = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, note, position, created_at, updated_at
`

type UpdateRoutineParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
	Name   string    `json:"name"`
	Note   string    `json:"note"`
}

func (q *Queries) UpdateRoutine(ctx context.Context, arg UpdateRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, updateRoutine,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Note,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Note,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
