// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, email_verified)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, password_hash, email_verified, handle, status, streak, load_target, created_at, updated_at, dob
`

type CreateUserParams struct {
	Name          string  `json:"name"`
	Email         string  `json:"email"`
	PasswordHash  *string `json:"passwordHash"`
	EmailVerified bool    `json:"emailVerified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Handle,
		&i.Status,
		&i.Streak,
		&i.LoadTarget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dob,
	)
	return i, err
}

const createUserSettings = `-- name: CreateUserSettings :one
INSERT INTO user_settings (user_id) VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING user_id, units, notifications, connected_apps, body_weight_kg, updated_at, notification_prefs, goals
`

func (q *Queries) CreateUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, createUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Units,
		&i.Notifications,
		&i.ConnectedApps,
		&i.BodyWeightKg,
		&i.UpdatedAt,
		&i.NotificationPrefs,
		&i.Goals,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, email_verified, handle, status, streak, load_target, created_at, updated_at, dob FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Handle,
		&i.Status,
		&i.Streak,
		&i.LoadTarget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dob,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, email_verified, handle, status, streak, load_target, created_at, updated_at, dob FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Handle,
		&i.Status,
		&i.Streak,
		&i.LoadTarget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dob,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, units, notifications, connected_apps, body_weight_kg, updated_at, notification_prefs, goals FROM user_settings WHERE user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Units,
		&i.Notifications,
		&i.ConnectedApps,
		&i.BodyWeightKg,
		&i.UpdatedAt,
		&i.NotificationPrefs,
		&i.Goals,
	)
	return i, err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = true, updated_at = now() WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash *string   `json:"passwordHash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name        = COALESCE($1, name),
    handle      = COALESCE($2, handle),
    status      = COALESCE($3, status),
    load_target = COALESCE($4, load_target),
    dob         = COALESCE($5, dob),
    updated_at  = now()
WHERE id = $6
RETURNING id, name, email, password_hash, email_verified, handle, status, streak, load_target, created_at, updated_at, dob
`

type UpdateUserProfileParams struct {
	Name       *string     `json:"name"`
	Handle     *string     `json:"handle"`
	Status     *string     `json:"status"`
	LoadTarget *int32      `json:"loadTarget"`
	Dob        pgtype.Date `json:"dob"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Name,
		arg.Handle,
		arg.Status,
		arg.LoadTarget,
		arg.Dob,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Handle,
		&i.Status,
		&i.Streak,
		&i.LoadTarget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dob,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE user_settings
SET units          = COALESCE($1, units),
    notifications  = COALESCE($2, notifications),
    connected_apps = COALESCE($3, connected_apps),
    body_weight_kg = COALESCE($4, body_weight_kg),
    goals          = COALESCE($5, goals),
    updated_at     = now()
WHERE user_id = $6
RETURNING user_id, units, notifications, connected_apps, body_weight_kg, updated_at, notification_prefs, goals
`

type UpdateUserSettingsParams struct {
	Units         *string        `json:"units"`
	Notifications *bool          `json:"notifications"`
	ConnectedApps *int32         `json:"connectedApps"`
	BodyWeightKg  pgtype.Numeric `json:"bodyWeightKg"`
	Goals         []byte         `json:"goals"`
	UserID        uuid.UUID      `json:"userId"`
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.Units,
		arg.Notifications,
		arg.ConnectedApps,
		arg.BodyWeightKg,
		arg.Goals,
		arg.UserID,
	)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Units,
		&i.Notifications,
		&i.ConnectedApps,
		&i.BodyWeightKg,
		&i.UpdatedAt,
		&i.NotificationPrefs,
		&i.Goals,
	)
	return i, err
}
